#include "language.h"
#include "user_data.h"
#include <stdlib.h>
#include <stdio.h>

static const char *lang_str[LANG_STR_ID_TOTAL][LANG_TOTAL] =
	{
		// layout home
		{"Door1", "درب 1"},
		{"Door2", "درب 2"},
		{"CCTV1", "مداربسته 1"},
		{"CCTV2", "مداربسته 2"},
		{"Language", "زبان"},
		{"Bell", "زنگ"},
		{"Recording", "ضبط"},
		{"Lock", "قفل"},
		{"Monday", "دوشنبه"},
		{"Tuesday", "سه شنبه"},
		{"Wedday", "چهار شنبه"},
		{"Thurday", "پنجشنبه"},
		{"Friday", "جمعه"},
		{"Satday", "شنبه"},
		{"Sunday", "یکشنبه"},
		{"Monitor", "مانیتور"},
		{"CCTV", "مداربسته "},
		{"Security", " امنیت"},
		{"Elevator", "میز"},
		// layout camera
		{"Brightness", "روشنایی"},
		{"Color", "رنگ"},
		{"Contrast", "کنتراست"},
		{"Cam1&2", "درب 1و2"},
		{"Change", "تغییر"},
		{"Zoom", "بزرگنمایی"},
		{"Open", "باز کردن"},
		{"Encoded", "عکسبرداری"},
		{"s", "ثانیه"},
		{"Door Open", "بازکردن درب"},
		// layout language
		{"Language", "زبان"},
		{"English", "English"},
		{"فارسی", "فارسی"},
		// layout bell
		{"Bell Volume", "صدای زنگ"},
		{"Door1 Ring", "زنگ درب 1"},
		{"Door2 Ring", "زنگ درب 2"},
		{"Ringtone", "ملودی زنگ"},
		// layout calendar
		{"Clock Display", "نمایش ساعت"},
		{"Clock Color", "رنگ ساعت"},
		{"Persian", "شمسی"},
		{"Western", "میلادی"},
		{"Year", "سال"},
		{"Month", "ماه"},
		{"Day", "روز"},
		{"Hour", "ساعت"},
		{"Minute", "دقیقه"},
		// layout memory
		{"Image", "عکس"},
		{"picture record", "عکس"},
		{"Video", "فیلم"},
		{"video record", "فیلم"},
		{"Mode", "حالت"},
		{"Prev", "قبلی"},
		{"Play", "پخش"},
		{"Stop", "توقف"},
		{"Next", "بعدی"},
		{"To delete current video ?", "این ویدیو فعلی حذف شود؟"},
		{"To delete current photo ?", "این عکس فعلی حذف شود؟"},
		{"Delete All Video ?", "حذف تمام ویدیوهای؟"},
		{"Delete All Picture ?", "حذف تمام تصاویر؟"},
		// {"Delete All Call Record ?", "حذف تمام سوابق تماس؟"},
		// layout recording
		{"NO Image", "فاقد عکس"},
		{"NO Video", "فاقد فیلم"},
		{"NO SD", "فاقد کارت حافظه"},
		{"call record", "ضبط صدا"},
		{"Recording time", "مدت ضبط"},
		{"Device", "دستگاه"},
		{"Recording mode", "حالت ضبط"},
		{"Call time", "مدت تماس"},
		{"State", "وضعیت"},
		{"Manual", "دستی"},
		{"Auto", "آتوماتیک"},
		{"Motion", "حرکت"},
		{"Reject", " رد کردن"},
		{"Answered", "پاسخ داده"},
		{"Photo 1 (Flash)", "عکس ۱ (فلاش)"},
		{"Photo 2 (SD)", "عکس ۲ (SD)"},
		// layout security
		{"Security Sensor 1", "نگهبانی 1"},
		{"Auto Rec", "التسجيل التلقائي"},
		{"Security 1 sensor status", " يرجى التحقق من حالة مستشعر الأمان 1"},
		{"Security 2 sensor status", "يرجى التحقق من حالة مستشعر الأمان 2"},
		{"Security Sensor 1", "جهاز استشعار الأمان  1"},
		{"Security Sensor 2", "جهاز استشعار الأمان  2"},
		{"Security function is running", "وظيفة الأمان قيد التشغيل"},
		{"Check Security 1, 2 sensor status", "يرجى التحقق من حالة مستشعر الأمان  1  ،  2 "},
		{"Sensor not selected", "لا استشعار مختارة"},
		{"Execution", "|تنفيذ"},
		{"End", "أنهاء"},
		{"Please check sensor state", "يرجى التحقق من حالة الاستشعار"},
		// layout alarm_list
		{"Delete File...", "حذف الملف"},
		{"Security Sensor 1 Emergency", "مستشعر الأمان 1  الطوارئ الأمنية"},
		{"Security Sensor 2 Emergency", "مستشعر الأمان 2  الطوارئ الأمنية"},
		{"Emergency Records", "سجلات الطوارئ"},
		// layout motion_detection
		{"Low", "منخفض"},
		{"Middle", "متوسط"},
		{"High", "عالی"},
		// layout intercom
		{"Room 1", "اتاق 1"},
		{"Room 2", "اتاق 2"},
		{"Room 3", "اتاق 3"},
		{"Room 4", "اتاق 4"},
		{"Local Address", "آدرس داخلی"},
		{"Input Room No.", "ورودی شماره اتاق"},
		{"Set OK", "تایید تنظیمات"},
		{"Receive Intercom", "ارتباط داخلی فعال"},
		{"Call Number", "شماره تماس"},
		{"Input Password", "رمز عبور را وارد کنید"},
		{"Guard", "نگهبانی"},
		{"Guard", "نگهبانی"},
		{"Guard", "نگهبانی"},
		{"OK", "تایید"},
		{"Take Handset", " گیرید سیم‌گیر"},
		{"Local", "داخلی"},
		{"Calling...", "...در حال تماس"},
		{"Line Busy", "خط اشغال است"},
		{"Unit Busy", "واحد اشغال است"},
		{"No Response", "بدون پاسخ"},
		{"Error", "خطا"},
		{"Ring Volume", "ولوم زنگ"},
		{"Ring From", "تماس از"},
		{"Calling To", "تماس با"},
		{"Talking With", "مکالمه با"},
		{"Disconnect", "قطع ارتباط"},
		{"End", "پایان ارتباط"},
		{"No Answer", "عدم پاسخگویی"},
		{"Room NO.", "شماره اتاق"},
		{"Input Call Number.", "شماره تماس را وارد کنید."},
		// layout setting
		{"Room NO. Setting", "تنظیمات شماره اتاق"},
		{"Room Id", "هویت اتاق"},
		{"SD Card", "کارت حافظه"},
		{"Reset", "تنظیم اولیه"},
		{"About", "درباره"},
		{"System", "سیستم"},
		{"Time", "زمان"},
		{"Sound", "صدا"},
		{"security password", "رمز عبور نگهبانی"},
		{"Factory setting", "تنظیمات کارخانه"},
		{"Formatting SD", "فرمت کردن کارت حافظه"},
		{"Backup local photos to SDcard", "کپی تصاویر به کارت حافظه"},
		{"Motion detection", "تشخیص حرکت"},
		{"Screen adjust", "نمایش صفحه"},
		{"System keytone", "نگهبانی"},
		{"Song", "موزیک"},
		{"Ring volume setting", "تنظیم صدای زنگ"},
		{"Call Volume Setting", "تنظیم صدای تماس"},
		{"Call Volume", "صدای تماس"},
		{"Off", "إيقاف"},
		{"On", "روشن"},
		{"Factory Setting ?", "تنظیمات کارخانه؟"},
		{"Formatting SD ?", "فرمت کردن کارت حافظه؟"},
		{"Back up local photos to SD card ?", "کپی تصاویر به کارت حافظه؟"},
		// layout setting password
		{"Enter Password", "رمز عبور را وارد کنید"},
		{"Password is too simple", "رمز عبور نمی تواند ساده باشد"},
		{"Password Error", "كلمة المرور غير متطابقة"},
		{"Password Reset", "تنظیم رمز عبور"},
		{"Please enter the new password:"},
		{"Confirm Password", "تایید رمز عبور"},
		{"Apply", "تایید"},
		// layout setting detection
		{"Open detection", "تشخیص حرکت"},
		{"Camera Select", "انتخاب دوربین"},
		{"Storage mode", "حالت ذخیره"},
		{"Sensitivity setting", "تنظیم نزدیکی"},
		{"Recording duration", "مدت ضبط"},
		{"Bright screen", "نمایش صفحه بزرگ"},
		{"Time period control", "کنترل زمان"},
		// layout record
		{"Auto Recording", "ضبط اتوماتیک"},
		{"Record Mode", "نوع ضبط"},
		{"Image", "عکس"},
		{"Video", "فیلم"},
		{"Please insert SD Card to record video !", "لطفا کارت حافظه را برای ضبط فیلم وارد کنید!"},
		// layout room id
		{"Room ID", "شناسایی اتاق"},
		{"Successful", "موفقیت"},
		// layout delete
		{"Delete All Pictures ?", "حذف تمامی عکس ها؟"},
		{"Delete All Videos ?", "حذف تمامی فیلم ها؟"},
		{"Deleting...", "در حال حذف..."},
		// layout sd card
		{"Copy To SD ?", "کپی در کارت حافظه؟"},
		{"Copying...", "در حال کپی..."},
		{"Format SD ?", "فرمت کارت حافظه؟"},
		{"Formating", "در حال فرمت"},
		{"Format OK", "تایید فرمت"},
		// layout reset
		{"Factory Setting ?", "تنظیمات کارخانه؟"},
		// layout about
		{"Taba", "تابا"},
		{"Model", "مدل"},
		{"Software version", "نسخه نرم افزار"},
		// common
		{"Home", "صفحه اصلی"},
		{"Calendar", "تقویم"},
		{"Intercom", "ارتباط داخلی"},
		{"Setting", "تنظیمات"},
		{"Exit", "خروج"},
		{"CAM1", "درب 1"},
		{"CAM2", "درب 2"},
		{"Record", "ضبط"},
		{"Delete", "حذف"},
		{"Back", "بازگشت"},
		{"YES", "بله"},
		{"NO", "خیر"},
		{"Confirm", "ثابت کنید"},
		{"No SD", "فاقد کارت حافظه"},
		{"Return", "بازگشت"},
		{"Memory", "حافظه"},
		{"Copy&Delete", "کپی و حذف"},
		{"Auto photo", "عکس اتوماتیک"},
		{"Auto video", "فیلم اتوماتیک"},
		{"Motion CCTV1", "حرکت مداربسته 1"},
		{"Motion CCTV2", "حرکت مداربسته 2"},
		{"Volume", "صدا"},
		{"Cam1 Melody", "ملودی کم1"},
		{"Cam2 Melody", "ملودی کم۲"},
		{"Copy to SD", "کپی به SD"},
		{"Delete Video", "حذف ویدیو"},
		{"Delete Photo (SD)", "حذف عکس (SD)"},
		{"Delete Photo (Flash)", "حذف عکس (فلیش)"},
		{"Are you sure Copy to SD?", "آیا مطمئن هستید که کپی به SD انجام دهید؟"},
		{"Are you sure delete photo(Flash)?", "آیا مطمئنید که عکس (فلیش) را حذف می‌کنید؟"},
		{"Reset system", "ریست سیستم"},
		{"Media", "رسانه"},
		{"SET NO", "شماره تنظیم"},
		{"Are you sure delete the video?", "آیا مطمئن هستید ویدیو را حذف می‌کنید؟"},
		{"Are you sure delete photo(Flash)?", "آیا مطمئن هستید عکس (فلش) را حذف می‌کنید؟"},
		{"Are you sure delete photo(SD)?", "آیا مطمئن هستید عکس (SD) را حذف می‌کنید؟"},
		{"Enter password", "لطفا رمز عبور را وارد کنید"},
		{"Auto Record", "ثبت خودکار"},
		//left head
		{"Media", "رسانه"},
		{"Time", "زمان"},
		{"Menu", "منو"},
		{"Init", "راه‌اندازی"},
		{"Setting", "تنظیمات"},
		{"Memory", "حافظه"},
		//calling
		{"calling...","در حال تماس..."},

};

const char *str_get(layout_lang_id id)
{
	return lang_str[id][user_data_get()->setting.language];
}
